# This file was generated by GoReleaser. DO NOT EDIT.
cask "pkg-age-check" do
  name "pkg-age-check"
  desc "Check package release age and stability windows."
  homepage "https://github.com/abandisch/pkg-age-check"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pkg-age-check"

  on_macos do
    on_intel do
      url "https://github.com/abandisch/pkg-age-check/releases/download/v#{version}/pkg-age-check_#{version}_macOS_amd64.tar.gz"
      sha256 "2ab0b10813bcaac4a26e71356286b464465399872a878a0dadb38d88ae00c52a"
    end
    on_arm do
      url "https://github.com/abandisch/pkg-age-check/releases/download/v#{version}/pkg-age-check_#{version}_macOS_arm64.tar.gz"
      sha256 "502bf94d808fdff75f01eb02241e405cd58dc77ea300631e4a3a7382ac1b827c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/abandisch/pkg-age-check/releases/download/v#{version}/pkg-age-check_#{version}_linux_amd64.tar.gz"
      sha256 "2ea9537c360cdd1d685d74de959433151b6f5a4797d88e23a8c262e052ad1281"
    end
    on_arm do
      url "https://github.com/abandisch/pkg-age-check/releases/download/v#{version}/pkg-age-check_#{version}_linux_arm64.tar.gz"
      sha256 "7389957d1f92f749ef2ae873ea5796b7d821c19f28a71c68c01ab7106df3865b"
    end
  end

  # No zap stanza required
end
