# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PkgAgeCheck < Formula
  desc "Check package release age and stability windows."
  homepage "https://github.com/abandisch/pkg-age-check"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/abandisch/pkg-age-check/releases/download/v0.1.4/pkg-age-check_0.1.4_macOS_amd64.tar.gz"
      sha256 "176d37c43ca60c251024e3292f94228e98a23702dab41d75fccc4f12343bc47f"

      def install
        bin.install "pkg-age-check"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/abandisch/pkg-age-check/releases/download/v0.1.4/pkg-age-check_0.1.4_macOS_arm64.tar.gz"
      sha256 "e514bc665b2781c42475f646dcebf41aef20c210a606cbe0cc2176c7f65ebe45"

      def install
        bin.install "pkg-age-check"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/abandisch/pkg-age-check/releases/download/v0.1.4/pkg-age-check_0.1.4_linux_amd64.tar.gz"
      sha256 "891b38c825dba5ed8d5fd4adaa3a9eb1a15985ab95d2accc49f00303f137dd38"
      def install
        bin.install "pkg-age-check"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/abandisch/pkg-age-check/releases/download/v0.1.4/pkg-age-check_0.1.4_linux_arm64.tar.gz"
      sha256 "b5d783ecdf22363c5906e5c4b64d9e7dd1d0ed68ad8588610763906edeae4b8a"
      def install
        bin.install "pkg-age-check"
      end
    end
  end

  test do
    system "#{bin}/pkg-age-check", "--version"
  end
end
